name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Roda todo dia à meia-noite
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gera a Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: camilaisperling
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit e push do Snake
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
